### ISSUE TITLE
Crash when playing Assemble+

### ISSUE THREAD

**Issue by Much333n** [twanvl/sts-mad-science-mod#2]
I wanted to try your Char in Endless, it has been great fun so far but when i use assemble+ in a fight the game crashes after picking the parts (before shuffling).

I get the following Error:

`Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at madsciencemod.actions.unique.AssembleAction.update(AssembleAction.java:90)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2615)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)`

Seems to be a problem with your mod (or beta branch) , though i got more installed:

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (06-21-2018) BETA
 - ModTheSpire (2.7.0)

Mod list:
 - basemod (2.14.0)
 - STS_AlwaysWhale (0.0.1)
 - ReplayTheSpireMod (0.4.9)
 - betterrewardsmod (4.0.0)
 - customclimb (0.3.2)
 - fruitymod-sts (0.6.7)
 - MadScienceMod (0.1.5)
 - NecroMod

**Comment by twanvl** [comment]
This is fixed in the new release (v0.1.6)
