### ISSUE TITLE
Crash when buying Recycling Station at the store

### ISSUE THREAD

**Issue by Daenyth** [twanvl/sts-mad-science-mod#8]
```
21:47:59.999 INFO helpers.CardHelper> Obtained RecyclingStation (UNCOMMON). Creating new map entry.
21:47:59.999 INFO unlock.UnlockTracker> Already seen: RecyclingStation
21:48:00.033 INFO helpers.CardHelper> No need to track rarity type: SPECIAL
Exception: java.util.ConcurrentModificationException
21:48:00.041 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_152]
	at java.util.ArrayList$Itr.remove(ArrayList.java:873) ~[?:1.8.0_152]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2690) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:818) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:413) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
21:48:00.064 INFO core.CardCrawlGame> PAUSE()
21:48:00.065 INFO core.CardCrawlGame> Game shutting down...
21:48:00.065 INFO helpers.FileSaver> Save thread interrupted!
21:48:00.065 INFO helpers.FileSaver> Save thread will die now.
AL lib: (WW) FreeDevice: (0x7fcf8db44000) Deleting 19 Buffer(s)
```

[MAD_SCIENTIST.autosave.zip](https://github.com/twanvl/sts-mad-science-mod/files/2182270/MAD_SCIENTIST.autosave.zip)

**Comment by Daenyth** [comment]
```
Version Info:
 - Java version (1.8.0_152)
 - Slay the Spire (07-05-2018)
 - ModTheSpire (2.7.0)
Mod list:
 - basemod (2.15.0)
 - ReplayTheSpireMod (0.4.12)
 - MadScienceMod (0.1.8)
 - witchmod (0.9.1)
 - constructmod (0.7.2)
 - fruitymod-sts (0.6.9)

```

**Comment by twanvl** [comment]
The bug is actually caused by the `Grinning Jar` from the Replay the Spire mod. Obtaining a 12th card adds a `Pot of Greed` to your deck, which causes a crash when this happens while you are in a shop.
