### ISSUE TITLE
Failing to launch

### ISSUE THREAD

**Issue by wejami** [twanvl/sts-mad-science-mod#9]
I downloaded the file today and it is failing to launch.  Here is my MTS log:

 ------------------------

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (07-12-2018)
 - ModTheSpire (2.8.0)
Mod list:
 - basemod (2.15.0)
 - MadScienceMod (0.2.0)

Begin patching...
Finding core patches...
Finding patches...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.

Setting isModded = true...Done.

Adding ModTheSpire to version...Done.

Initializing mods...
libgdx version 1.9.5
01:35:15.058 INFO basemod.BaseMod> initializeGson
01:35:15.058 INFO basemod.BaseMod> initializeTypeMaps
01:35:15.074 INFO basemod.BaseMod> initializePowerMap
01:35:15.535 INFO basemod.BaseMod> initializeUnderscorePowerIDs
01:35:15.535 INFO basemod.BaseMod> initializeEncounters
01:35:15.582 INFO madsciencemod.MadScienceMod> begin editing colors

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:34)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:272)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: basemod.BaseMod.addColor(Ljava/lang/String;Lcom/badlogic/gdx/graphics/Color;Lcom/badlogic/gdx/graphics/Color;Lcom/badlogic/gdx/graphics/Color;Lcom/badlogic/gdx/graphics/Color;Lcom/badlogic/gdx/graphics/Color;Lcom/badlogic/gdx/graphics/Color;Lcom/badlogic/gdx/graphics/Color;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
	at madsciencemod.MadScienceMod.receiveEditColors(MadScienceMod.java:97)
	at madsciencemod.MadScienceMod.<init>(MadScienceMod.java:77)
	at madsciencemod.MadScienceMod.initialize(MadScienceMod.java:81)
	... 8 more

**Comment by twanvl** [comment]
You need a newer version of BaseMod, at least 2.16.
